schemaVersion: 1
categories:
  - id: consulting
    labels:
      fr: Conseil
      en: Consulting
  - id: technology
    labels:
      fr: Technologie
      en: Technology
  - id: cybersecurity
    labels:
      fr: Cybersécurité
      en: Cybersecurity
  - id: artificial-intelligence
    labels:
      fr: Intelligence artificielle
      en: Artificial intelligence
  - id: media
    labels:
      fr: Média
      en: Media
